title: "Adventures of a System Admin: A Brief History"
description: > # this means to ignore newlines until "baseurl:"
  My awesome blog for Linux enthusiasts! In here, you can find the adventures
  of a system admin while he tries to become DevOps Engineer.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Armagan Karatosun # add your name
author-img: avatar.png # add your photo
about-author: Some stuff about me, more stuff about Linux.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: armagankaratosun # add your Github handle
social-linkedin: armagan-karatosun-15941182 # add your Linkedin handle
social-email: armagankaratosun@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: #


# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
